server:
  port: 8811

spring:
  application:
    name: mall-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  devtools:
    livereload:
      port: 35731
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://127.0.0.1:8820
          predicates:
            - Path=/product/**

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8810/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30