server:
  port: 8811

spring:
  application:
    name: mall-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://127.0.0.1:8828
          predicates:
            - Path=/auth/**
        - id: config
          uri: http://127.0.0.1:8812
          predicates:
            - Path=/config/**
        - id: product
          uri: http://127.0.0.1:8820
          predicates:
            - Path=/product/**
        - id: order
          uri: http://127.0.0.1:8821
          predicates:
            - Path=/order/**
        - id: user
          uri: http://127.0.0.1:8822
          predicates:
            - Path=/user/**
        - id: stock
          uri: http://127.0.0.1:8823
          predicates:
            - Path=/stock/**
        - id: system
          uri: http://127.0.0.1:8824
          predicates:
            - Path=/system/**
      default-filters:
        - StripPrefix=1

logging:
  level:
    com.sys.auth: debug
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8810/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

security:
  ignore-urls:
    - /auth/oauth/token