server:
  port: 8821

spring:
  application:
    name: mall-order-manage
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  devtools:
    livereload:
      port: 35741
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: '263661'
    hikari:
      # 最小空闲连接数
      minimum-idle: 5
      # 连接允许空闲最大时间
      idle-timeout: 180000
      # 连接池最大连接数，包括使用和空闲
      maximum-pool-size: 10
      # 连接自动提交
      auto-commit: true
      # 连接池名称
      pool-name: OrderHikariCP
      # 池中连接最长生命周期
      max-lifetime: 1800000
      # 数据库连接超时时间
      connection-timeout: 30000

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8810/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.sys.order: debug