server:
  port: 8810

spring:
  application:
    name: mall-eureka
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  devtools:
    livereload:
      port: 35730

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
