server:
  port: 8813

spring:
  application:
    name: mall-common

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8810/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30
