server:
  port: 8812

spring:
  application:
    name: mall-config
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `config_key`, `config_value` FROM td_sys_config WHERE `flag` = 1 AND `application` = ? AND `profile` = ? AND `label` = ?
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: '263661'
  rabbitmq:
    host: 127.0.0.1
    port: 5672

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8810/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.sys.config: debug

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
