server:
  port: 8812

spring:
  application:
    name: mall-config
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  devtools:
    livereload:
      port: 35732

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8810/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30
